homeassistant: true
mqtt:
  server: mqtt://192.168.50.50:1883
  user: mqtt-only
  password: getgetget^^^
  keepalive: 60
  reject_unauthorized: true
  version: 5
  topic: delz2mt
serial:
  port: /dev/ttyUSB0
frontend:
  port: 8099
permit_join: true
advanced:
  log_syslog:
    app_name: Zigbee2MQTT
    eol: /n
    host: localhost
    localhost: localhost
    path: /dev/log
    pid: process.pid
    port: 123
    protocol: tcp4
    type: '5424'
  output: attribute_and_json
devices:
  '0xcc86ecfffeb05501':
    friendly_name: curtain
    invert_cover: true
  '0x00124b0024ce5e4e':
    friendly_name: button
  '0x00124b0023b4d887':
    friendly_name: room-pir
  '0x00124b00250bf583':
    friendly_name: door-pir
  '0x847127fffe21af74':
    friendly_name: balcony-pir
  '0x943469fffec9539a':
    friendly_name: toilet-presence
  '0xa4c1388e2c730e1b':
    friendly_name: room-presence
  '0xcc86ecfffe4ea1cb':
    friendly_name: internet-plug
  '0xcc86ecfffef3c6fc':
    friendly_name: wifi-plug
  '0x04cd15fffe23ec21':
    friendly_name: knob
